---
#- name: Test
#  shell: /bin/echo "hello123"

- name: login to ocp
  command: "{{ OC_HOME}}/oc login -u openshift-dev -p devel"
- name: get project
  command: "{{OC_HOME}}/oc project apac-destinasia-travel"

- name: get service ip
  shell: "{{OC_HOME}}/oc get svc destinasia-rules-demo -n apac-destinasia-travel | /bin/awk 'NR > 1 {print $2}'"
  register: git_service_ip

- set_fact:
   git_svc_ip: "{{ git_service_ip.stdout }}"

- name: Show Service IP
  debug:
    msg: "{{ git_svc_ip }}"

- name: Create App
  command: "{{OC_HOME}}/oc new-app --template=decisionserver63-basic-s2i  --name=brms -l app=brms -p APPLICATION_NAME=brms -p SOURCE_REPOSITORY_URL=git://{{git_svc_ip}}:9418/destinasia -p CONTEXT_DIR=/discountRules -p SOURCE_REPOSITORY_REF=master -p KIE_CONTAINER_DEPLOYMENT='c2=techoffice:discountRules:1.0'  -p KIE_SERVER_USER=kieserver -p KIE_SERVER_PASSWORD=kieserver1!"
